# -*- coding: utf-8 -*-
"""Generate the case-study and article pages.

    python tools/build.py          # from the repository root

The site itself has no build step: this writes plain HTML files that are
committed and served as-is. The generator exists only so that thirteen pages
share one header, one footer and one set of styles instead of drifting.

After running this, run tools/csp.py to refresh the inline-script hashes.
"""
import io
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from content import CASE_STUDIES, ARTICLES  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = "https://humansofcoding.com"

# The line drawings reused from the home page's project cards.
THUMBS = {
    "a": '<rect x="72" y="16" width="56" height="118" rx="10"/><path d="M92 26h16"/>'
         '<rect x="82" y="40" width="36" height="20" rx="5"/>'
         '<path d="M82 70h36M82 80h24M82 90h30"/>'
         '<rect x="82" y="104" width="36" height="14" rx="7"/>',
    "b": '<rect x="26" y="24" width="148" height="102" rx="8"/><path d="M26 44h148"/>'
         '<path d="M40 60h40M40 72h56M40 84h32"/>'
         '<rect x="112" y="60" width="48" height="34" rx="6"/>'
         '<rect x="40" y="98" width="40" height="12" rx="6"/>',
    "c": '<rect x="34" y="30" width="132" height="90" rx="8"/><path d="M34 52h132"/>'
         '<circle cx="70" cy="86" r="18"/><path d="M70 68v18l12 8"/>'
         '<path d="M104 74h50M104 88h50M104 102h30"/>',
}

BRAND_SVG = (
    '<svg viewBox="0 0 44 44" fill="none" stroke="currentColor" stroke-width="2.6" '
    'stroke-linecap="round" stroke-linejoin="round">'
    '<path d="M22 3.5c10.2 0 18.5 8.3 18.5 18.5S32.2 40.5 22 40.5 3.5 32.2 3.5 22 11.8 3.5 22 3.5Z"/>'
    '<path d="M15 18.5v9M15 22.6h6.5M21.5 18.2v9.2"/>'
    '<path d="M27 27.5c3.4 0 5.6-2.1 5.6-5.3S30.4 17 27 17"/></svg>'
)

MAILTO = ("mailto:adil@humansofcoding.com"
          "?subject=Free%20call%20request%20-%20HumansOfCoding")
INSTAGRAM = "https://instagram.com/humansofcoding"

# Both inline scripts are byte-identical to the ones in index.html, so the
# CSP hashes computed for that page cover these pages too.
HTTPS_SCRIPT = '''<script>
/* Send visitors to HTTPS. GitHub Pages' own "Enforce HTTPS" does this at the
   server level; this is the belt-and-braces version and is harmless once that
   setting is on (GitHub redirects first, so this never runs). Skipped for
   localhost and for opening the file directly from disk. */
(function () {
  var h = location.hostname;
  if (location.protocol === "http:" && h !== "localhost" && h !== "127.0.0.1") {
    location.replace("https://" + location.host + location.pathname + location.search + location.hash);
  }
})();
</script>'''

BOOT_SCRIPT = '''<script>
(function () {
  var d = document.documentElement, t = null, p = null;
  try {
    t = localStorage.getItem("hoc-theme");
    p = localStorage.getItem("hoc-palette");
  } catch (e) {}
  // never trust stored values verbatim
  if (t !== "dark" && t !== "light") t = null;
  if (["blue", "green", "slate", "ocean", "rainbow"].indexOf(p) === -1) p = "blue";
  d.classList.add("js");
  d.setAttribute("data-theme", t || (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light"));
  d.setAttribute("data-palette", p);
})();
</script>'''

BEACON = ('<!-- Cloudflare Web Analytics. Privacy-friendly and cookie-free: the numbers go\n'
          '     to the Cloudflare dashboard, not onto this page. The token is public. -->\n'
          '<script type="module" src="https://static.cloudflareinsights.com/beacon.min.js" '
          'data-cf-beacon=\'{"token": "16ba7bce6bf54d6fa4327ecd5912dfb1"}\'></script>')

CSP = ('<meta http-equiv="Content-Security-Policy" content="default-src \'self\'; '
       'base-uri \'self\'; object-src \'none\'; form-action \'none\'; '
       'script-src \'self\' https://static.cloudflareinsights.com {hashes}; '
       'style-src \'self\' \'unsafe-inline\'; font-src \'self\'; img-src \'self\' data:; '
       'connect-src \'self\' https://cloudflareinsights.com; upgrade-insecure-requests" />')


def head(title, description, canonical, jsonld):
    """The <head> for a page one directory below the site root."""
    return u'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />

<!--
  Content Security Policy. GitHub Pages cannot send real headers, so this is
  the meta form. The hashes cover the inline scripts below and are generated by
  tools/csp.py — regenerate them if you edit any inline script.
-->
{csp}
{https}
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
<meta name="referrer" content="strict-origin-when-cross-origin" />
<meta name="theme-color" content="#f6f9fd" media="(prefers-color-scheme: light)" />
<meta name="theme-color" content="#0b1219" media="(prefers-color-scheme: dark)" />

<title>{title}</title>
<meta name="description" content="{description}" />
<meta name="author" content="Adil — HumansOfCoding" />
<link rel="canonical" href="{canonical}" />

<meta property="og:type" content="article" />
<meta property="og:site_name" content="HumansOfCoding" />
<meta property="og:title" content="{title}" />
<meta property="og:description" content="{description}" />
<meta property="og:url" content="{canonical}" />
<meta property="og:image" content="{site}/assets/og-image.svg" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="{title}" />
<meta name="twitter:description" content="{description}" />
<meta name="twitter:image" content="{site}/assets/og-image.svg" />

<link rel="icon" href="../assets/favicon.svg" type="image/svg+xml" />
<link rel="apple-touch-icon" href="../assets/favicon.svg" />

<link rel="preload" href="../assets/fonts/inter-latin.woff2" as="font" type="font/woff2" crossorigin />
<link rel="preload" href="../assets/fonts/bricolage-grotesque-latin.woff2" as="font" type="font/woff2" crossorigin />
<link rel="stylesheet" href="../style.css" />

<!-- Tiny bootstrap: marks that JS is on and applies the saved theme before the
     first paint, so dark-mode users never see a flash of light. -->
{boot}

<script type="application/ld+json">
{jsonld}
</script>
</head>
'''.format(csp=CSP.format(hashes="{hashes}"), https=HTTPS_SCRIPT, boot=BOOT_SCRIPT,
           title=title, description=description, canonical=canonical,
           site=SITE, jsonld=jsonld)


def chrome_open(active):
    """Header, translation notice and mobile menu. `active` marks the nav item."""
    def cls(name):
        return ' class="is-active"' if name == active else ''
    return u'''<body>
<a class="skip-link" href="#main">Skip to content</a>
<div class="progress" aria-hidden="true"><span id="progressBar"></span></div>

<header class="nav" id="nav">
  <div class="container nav__inner">
    <a class="brand" href="../index.html" aria-label="HumansOfCoding home">
      <span class="brand__mark" aria-hidden="true">{brand}</span>
      <span class="brand__text">HumansOfCoding</span>
    </a>

    <nav class="nav__links" aria-label="Primary">
      <a href="../index.html#services">Services</a>
      <a href="../index.html#industries">Industries</a>
      <a href="../case-studies/"{cs}>Case Studies</a>
      <a href="../articles/"{ar}>Articles</a>
      <a href="../index.html#about">About</a>
    </nav>

    <div class="nav__actions">
      <div class="lang">
        <svg class="lang__globe" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c2.6 2.7 4 5.8 4 9s-1.4 6.3-4 9c-2.6-2.7-4-5.8-4-9s1.4-6.3 4-9Z"/></svg>
        <select class="lang__select" id="langSelect" aria-label="Language"></select>
        <svg class="lang__caret" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg>
      </div>
      <div class="appear">
        <button class="icon-btn" id="appearBtn" type="button" aria-label="Switch colour theme"
                aria-expanded="false" aria-haspopup="true" aria-controls="appearPanel">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <path d="M12 3a9 9 0 1 0 0 18c1 0 1.7-.8 1.7-1.7 0-.5-.2-.9-.5-1.2-.3-.3-.5-.7-.5-1.1 0-.9.8-1.7 1.7-1.7H16a5 5 0 0 0 5-5c0-4-4-7.3-9-7.3Z"/>
            <circle cx="7.6" cy="11.6" r="1.1" fill="currentColor" stroke="none"/>
            <circle cx="11" cy="7.4" r="1.1" fill="currentColor" stroke="none"/>
            <circle cx="16" cy="9" r="1.1" fill="currentColor" stroke="none"/>
          </svg>
        </button>

        <div class="appear__panel" id="appearPanel" hidden>
          <div class="appear__row" role="group" aria-label="Switch colour theme">
            <button type="button" class="appear__mode" data-mode="light" aria-label="Light">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><circle cx="12" cy="12" r="4.2"/><path d="M12 2.6v2.2M12 19.2v2.2M2.6 12h2.2M19.2 12h2.2M5.3 5.3l1.6 1.6M17.1 17.1l1.6 1.6M18.7 5.3l-1.6 1.6M6.9 17.1l-1.6 1.6"/></svg>
            </button>
            <button type="button" class="appear__mode" data-mode="dark" aria-label="Dark">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20 14.2A8.4 8.4 0 0 1 9.8 4a8.6 8.6 0 1 0 10.2 10.2Z"/></svg>
            </button>
            <button type="button" class="appear__mode" data-mode="system" aria-label="System">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="4.5" width="18" height="13" rx="2.5"/><path d="M9 21h6M12 17.5V21"/></svg>
            </button>
          </div>

          <div class="appear__row appear__row--swatches" role="group" aria-label="Colour">
            <button type="button" class="appear__sw" data-palette="blue" aria-label="Blue"><i style="background:#0f6ccc"></i></button>
            <button type="button" class="appear__sw" data-palette="green" aria-label="Green"><i style="background:#12784a"></i></button>
            <button type="button" class="appear__sw" data-palette="slate" aria-label="Slate"><i style="background:#445468"></i></button>
            <button type="button" class="appear__sw" data-palette="ocean" aria-label="Ocean"><i style="background:linear-gradient(135deg,#0b6a92,#38bdf8)"></i></button>
            <button type="button" class="appear__sw" data-palette="rainbow" aria-label="Rainbow"><i style="background:linear-gradient(100deg,#2563eb,#7028c8 34%,#c026d3 66%,#db2777)"></i></button>
          </div>
        </div>
      </div>
      <a class="btn btn--primary btn--sm nav__cta" data-link="call" href="{mailto}">Free Call</a>
      <button class="burger" id="burger" type="button" aria-label="Open menu" aria-expanded="false" aria-controls="mobileMenu">
        <span></span><span></span><span></span>
      </button>
    </div>
  </div>
</header>

<!-- Machine-translation notice (only shown when a translation is active) -->
<div class="tnote" id="transNote" hidden>
  <div class="container tnote__inner">
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 3.5 21 20H3l9-16.5Z"/><path d="M12 10v4M12 17h.01"/></svg>
    <p id="transNoteText"></p>
    <button type="button" id="transNoteLink" class="tnote__link"></button>
    <button type="button" id="transNoteOk" class="tnote__ok"></button>
  </div>
</div>

<div class="menu" id="mobileMenu" hidden>
  <nav class="menu__inner" aria-label="Mobile">
    <a href="../index.html#services"><span>01</span> Services</a>
    <a href="../index.html#human"><span>02</span> Human + AI</a>
    <a href="../index.html#industries"><span>03</span> Industries</a>
    <a href="../index.html#mvp"><span>04</span> MVP · ₹20,000</a>
    <a href="../case-studies/"><span>05</span> Case Studies</a>
    <a href="../articles/"><span>06</span> Articles</a>
    <a href="../index.html#about"><span>07</span> About Adil</a>
    <a href="../index.html#contact"><span>08</span> Contact</a>
    <div class="menu__cta">
      <a class="btn btn--primary btn--block" data-link="call" href="{mailto}">Book a Free Call</a>
      <a class="btn btn--ghost btn--block" data-link="instagram" href="{ig}">DM @humansofcoding</a>
    </div>
  </nav>
</div>

<main id="main">
'''.format(brand=BRAND_SVG, mailto=MAILTO, ig=INSTAGRAM,
           cs=cls("case-studies"), ar=cls("articles"))


CHROME_CLOSE = u'''</main>

<footer class="footer">
  <div class="container footer__inner">
    <div class="footer__brand">
      <a class="brand" href="../index.html" aria-label="HumansOfCoding home">
        <span class="brand__mark" aria-hidden="true">{brand}</span>
        <span class="brand__text">HumansOfCoding</span>
      </a>
      <p class="footer__tag">Apps • Websites • Software</p>
    </div>

    <nav class="footer__nav" aria-label="Footer">
      <a href="../index.html#services">Services</a>
      <a href="../index.html#mvp">MVP ₹20,000</a>
      <a href="../case-studies/">Case Studies</a>
      <a href="../articles/">Articles</a>
      <a href="../index.html#about">About</a>
      <a href="../index.html#contact">Contact</a>
    </nav>

    <div class="footer__social">
      <a class="footer__ig" data-link="instagram" href="{ig}">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5.5"/><circle cx="12" cy="12" r="4.2"/><path d="M17.4 6.6h.01"/></svg>
        @humansofcoding
      </a>
    </div>
  </div>
  <div class="container footer__bottom">
    <p>© 2026 HumansOfCoding. All rights reserved.</p>
    <p class="footer__made">Built by humans, in code. <span aria-hidden="true">✏️</span></p>
  </div>
</footer>

<div class="mobile-bar" id="mobileBar">
  <a class="btn btn--primary btn--block" data-link="call" href="{mailto}">Book a Free Call</a>
  <a class="mobile-bar__ig" data-link="instagram" href="{ig}" aria-label="DM us on Instagram">
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5.5"/><circle cx="12" cy="12" r="4.2"/><path d="M17.4 6.6h.01"/></svg>
  </a>
</div>

<script src="../i18n.js" defer></script>
<script src="../script.js" defer></script>

{beacon}
</body>
</html>
'''.format(brand=BRAND_SVG, mailto=MAILTO, ig=INSTAGRAM, beacon=BEACON)


def cta_block(title, sub):
    return u'''<section class="cta">
  <div class="container cta__inner">
    <h2 class="cta__title">{title}</h2>
    <p class="cta__sub">{sub}</p>
    <div class="cta__actions">
      <a class="btn btn--primary btn--lg" data-link="call" href="{mailto}">Book a FREE Call</a>
      <a class="btn btn--outline btn--lg" data-link="instagram" href="{ig}">DM @humansofcoding</a>
    </div>
    <p class="cta__note">Free 20-min idea call · No obligation</p>
  </div>
</section>
'''.format(title=title, sub=sub, mailto=MAILTO, ig=INSTAGRAM)


def breadcrumb(section, section_url, current):
    return u'''  <nav class="crumb" aria-label="Breadcrumb">
    <a href="../index.html">Home</a>
    <span aria-hidden="true">/</span>
    <a href="{url}">{section}</a>
    <span aria-hidden="true">/</span>
    <span aria-current="page">{current}</span>
  </nav>
'''.format(section=section, url=section_url, current=current)


# --------------------------------------------------------------------------
# case studies
# --------------------------------------------------------------------------

def case_study_page(cs, others):
    jsonld = u'''{{
  "@context": "https://schema.org",
  "@type": "CreativeWork",
  "name": "{title}",
  "abstract": "{summary}",
  "creator": {{ "@type": "Organization", "name": "HumansOfCoding" }},
  "url": "{site}/case-studies/{slug}.html",
  "isAccessibleForFree": true,
  "disambiguatingDescription": "Example build. HumansOfCoding is a new studio; this describes a project the studio is set up to deliver, not completed client work."
}}'''.format(title=cs["title"].replace("&amp;", "and"), summary=cs["summary"],
             site=SITE, slug=cs["slug"])

    out = [head("%s — Case Study | HumansOfCoding" % cs["title"].replace("&amp;", "&amp;"),
                cs["summary"],
                "%s/case-studies/%s.html" % (SITE, cs["slug"]),
                jsonld),
           chrome_open("case-studies")]

    out.append(u'''<article class="doc">
  <div class="container doc__head">
''')
    out.append(breadcrumb("Case Studies", "../case-studies/", cs["title"]))
    out.append(u'''    <span class="chips"><span class="proj__flag">Example build</span><span class="proj__cat">{cat}</span></span>
    <h1 class="doc__title">{title}</h1>
    <p class="doc__lead">{summary}</p>
    <div class="doc__thumb" aria-hidden="true">
      <svg viewBox="0 0 200 150" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">{thumb}</svg>
    </div>
  </div>

  <div class="container prose">
    <p class="note note--flag"><strong>This is an example build.</strong> HumansOfCoding
    is a new studio and has no client work to show yet. This page describes how this
    project would be scoped and built — the thinking you would get on a real one.
    Nothing here is a past client, and no numbers on this page are results.</p>

    <h2>The situation</h2>
'''.format(cat=cs["category"], title=cs["title"], summary=cs["summary"],
           thumb=THUMBS[cs["thumb"]]))

    for para in cs["situation"]:
        out.append(u"    <p>%s</p>\n" % para)

    out.append(u"\n    <h2>What we'd build first</h2>\n    <dl class=\"speclist\">\n")
    for name, body in cs["scope"]:
        out.append(u"      <dt>%s</dt>\n      <dd>%s</dd>\n" % (name, body))
    out.append(u"    </dl>\n")

    out.append(u"\n    <h2>What we'd leave out of version one</h2>\n"
               u"    <p>Not because these are bad ideas — because each one is better "
               u"designed once the first version has told you something.</p>\n    <ul>\n")
    for item in cs["excluded"]:
        out.append(u"      <li>%s</li>\n" % item)
    out.append(u"    </ul>\n")

    out.append(u"\n    <h2>How it's put together</h2>\n    <dl class=\"speclist speclist--tight\">\n")
    for name, body in cs["stack"]:
        out.append(u"      <dt>%s</dt>\n      <dd>%s</dd>\n" % (name, body))
    out.append(u"    </dl>\n")

    out.append(u"\n    <h2>Roughly how it runs</h2>\n    <ol class=\"steps\">\n")
    for when, what in cs["timeline"]:
        out.append(u"      <li><strong>%s</strong> %s</li>\n" % (when, what))
    out.append(u"    </ol>\n")

    out.append(u'\n    <p class="note"><strong>Worth knowing.</strong> %s</p>\n'
               % cs["note"])

    out.append(u'''
    <p class="note note--price">MVPs start at <strong>₹20,000*</strong>. Final pricing
    depends on features and project scope. Third-party costs — cloud hosting, domains,
    external libraries, APIs, app-store fees and any other paid service — are billed
    separately and are not included.</p>
  </div>

  <div class="container related">
    <h2 class="related__title">Other example builds</h2>
    <div class="related__grid">
''')
    for other in others:
        out.append(u'''      <a class="card post-card" href="{slug}.html">
        <span class="proj__cat">{cat}</span>
        <h3>{title}</h3>
        <p>{summary}</p>
        <span class="link-arrow">Read it <span aria-hidden="true">→</span></span>
      </a>
'''.format(slug=other["slug"], cat=other["category"], title=other["title"],
           summary=other["summary"]))

    out.append(u'''    </div>
  </div>
</article>

''')
    out.append(cta_block("Want this built for your business?",
                         "Tell us what you're thinking. We'll figure out the next step together."))
    out.append(CHROME_CLOSE)
    return "".join(out)


def case_studies_index():
    jsonld = u'''{
  "@context": "https://schema.org",
  "@type": "CollectionPage",
  "name": "Case Studies — HumansOfCoding",
  "description": "Example builds showing how HumansOfCoding scopes and ships apps, websites and custom software.",
  "url": "%s/case-studies/"
}''' % SITE

    out = [head("Case Studies — Example Builds | HumansOfCoding",
                "How we scope and build apps, websites, dashboards and MVPs — "
                "six example builds with the scope, the stack, the timeline and "
                "what we would deliberately leave out of version one.",
                "%s/case-studies/" % SITE, jsonld),
           chrome_open("case-studies")]

    out.append(u'''<section class="section page-hero">
  <div class="container">
''')
    out.append(u'''    <nav class="crumb" aria-label="Breadcrumb">
      <a href="../index.html">Home</a>
      <span aria-hidden="true">/</span>
      <span aria-current="page">Case Studies</span>
    </nav>
''')
    out.append(u'''    <div class="sec-head">
      <span class="eyebrow"><i class="eyebrow__dot"></i>WHAT WE BUILD</span>
      <h1 class="sec-title">Case studies</h1>
      <p class="sec-sub">Six builds, taken apart. What the business problem is, what
      version one contains, what gets cut, how it's put together and how long it runs.</p>
    </div>

    <p class="note note--flag"><strong>Straight up: these are example builds.</strong>
    HumansOfCoding is new, so none of these are past clients and nothing here is a
    results claim. They're the products the studio is set up to ship, written out in
    the same detail you'd get on a real project. Yours would be the first on this wall.</p>

    <div class="cards post-grid">
''')
    for i, cs in enumerate(CASE_STUDIES):
        out.append(u'''      <a class="card post-card reveal" data-reveal style="--d:.{d}s" href="{slug}.html">
        <div class="post-card__thumb" aria-hidden="true">
          <svg viewBox="0 0 200 150" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">{thumb}</svg>
        </div>
        <span class="chips"><span class="proj__flag">Example build</span><span class="proj__cat">{cat}</span></span>
        <h2>{title}</h2>
        <p>{summary}</p>
        <span class="link-arrow">Read the case study <span aria-hidden="true">→</span></span>
      </a>
'''.format(d=(i * 6) + 4, slug=cs["slug"], thumb=THUMBS[cs["thumb"]],
           cat=cs["category"], title=cs["title"], summary=cs["summary"]))

    out.append(u'''    </div>
  </div>
</section>

''')
    out.append(cta_block("Want to be project #001?",
                         "Tell us what you're thinking. We'll figure out the next step together."))
    out.append(CHROME_CLOSE)
    return "".join(out)


# --------------------------------------------------------------------------
# articles
# --------------------------------------------------------------------------

def render_blocks(blocks):
    out = []
    for kind, value in blocks:
        if kind == "h2":
            out.append(u"    <h2>%s</h2>\n" % value)
        elif kind == "p":
            out.append(u"    <p>%s</p>\n" % value)
        elif kind == "quote":
            out.append(u"    <blockquote><p>%s</p></blockquote>\n" % value)
        elif kind in ("ul", "ol"):
            out.append(u"    <%s>\n" % kind)
            for item in value:
                out.append(u"      <li>%s</li>\n" % item)
            out.append(u"    </%s>\n" % kind)
    return "".join(out)


def article_page(art, others):
    jsonld = u'''{{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "headline": "{title}",
  "description": "{summary}",
  "datePublished": "{date}",
  "author": {{ "@type": "Person", "name": "Adil" }},
  "publisher": {{ "@type": "Organization", "name": "HumansOfCoding" }},
  "mainEntityOfPage": "{site}/articles/{slug}.html",
  "inLanguage": "en"
}}'''.format(title=art["title"], summary=art["summary"], date=art["date"],
             site=SITE, slug=art["slug"])

    out = [head("%s | HumansOfCoding" % art["title"], art["summary"],
                "%s/articles/%s.html" % (SITE, art["slug"]), jsonld),
           chrome_open("articles")]

    out.append(u'''<article class="doc">
  <div class="container doc__head">
''')
    out.append(breadcrumb("Articles", "../articles/", art["title"]))
    out.append(u'''    <span class="proj__cat">{tag}</span>
    <h1 class="doc__title">{title}</h1>
    <p class="doc__lead">{summary}</p>
    <p class="doc__meta">
      <span>By Adil</span>
      <span aria-hidden="true">·</span>
      <time datetime="{date}">{date_label}</time>
      <span aria-hidden="true">·</span>
      <span>{read}</span>
    </p>
  </div>

  <div class="container prose">
'''.format(tag=art["tag"], title=art["title"], summary=art["summary"],
           date=art["date"], date_label=art["date_label"], read=art["read"]))

    out.append(render_blocks(art["body"]))

    out.append(u'''  </div>

  <div class="container related">
    <h2 class="related__title">More articles</h2>
    <div class="related__grid">
''')
    for other in others:
        out.append(u'''      <a class="card post-card" href="{slug}.html">
        <span class="proj__cat">{tag}</span>
        <h3>{title}</h3>
        <p>{summary}</p>
        <span class="link-arrow">Read it <span aria-hidden="true">→</span></span>
      </a>
'''.format(slug=other["slug"], tag=other["tag"], title=other["title"],
           summary=other["summary"]))

    out.append(u'''    </div>
  </div>
</article>

''')
    out.append(cta_block("Got an idea you've been sitting on?",
                         "Book a free call. Worst case, you walk away with free advice on what to build first."))
    out.append(CHROME_CLOSE)
    return "".join(out)


def articles_index():
    jsonld = u'''{
  "@context": "https://schema.org",
  "@type": "Blog",
  "name": "Articles — HumansOfCoding",
  "description": "Plain-English writing about building software: MVPs, pricing, apps versus websites, and how AI actually fits into the work.",
  "url": "%s/articles/"
}''' % SITE

    out = [head("Articles — Plain-English Writing on Building Software | HumansOfCoding",
                "MVPs, what software actually costs, apps versus websites, and how "
                "AI fits into real engineering. Written by Adil, no jargon.",
                "%s/articles/" % SITE, jsonld),
           chrome_open("articles")]

    out.append(u'''<section class="section page-hero">
  <div class="container">
    <nav class="crumb" aria-label="Breadcrumb">
      <a href="../index.html">Home</a>
      <span aria-hidden="true">/</span>
      <span aria-current="page">Articles</span>
    </nav>

    <div class="sec-head">
      <span class="eyebrow"><i class="eyebrow__dot"></i>WRITING</span>
      <h1 class="sec-title">Articles</h1>
      <p class="sec-sub">What I've learned building software for eleven years, written
      for the person paying for it rather than the person writing it.</p>
    </div>

    <div class="cards post-grid">
''')
    for i, art in enumerate(ARTICLES):
        out.append(u'''      <a class="card post-card reveal" data-reveal style="--d:.{d}s" href="{slug}.html">
        <span class="proj__cat">{tag}</span>
        <h2>{title}</h2>
        <p>{summary}</p>
        <p class="post-card__meta"><time datetime="{date}">{date_label}</time> · {read}</p>
        <span class="link-arrow">Read it <span aria-hidden="true">→</span></span>
      </a>
'''.format(d=(i * 6) + 4, slug=art["slug"], tag=art["tag"], title=art["title"],
           summary=art["summary"], date=art["date"], date_label=art["date_label"],
           read=art["read"]))

    out.append(u'''    </div>
  </div>
</section>

''')
    out.append(cta_block("Rather just ask a person?",
                         "Book a free 20-minute call and ask whatever you like. No obligation."))
    out.append(CHROME_CLOSE)
    return "".join(out)


# --------------------------------------------------------------------------

def write(path, text):
    full = os.path.join(ROOT, path)
    folder = os.path.dirname(full)
    if not os.path.isdir(folder):
        os.makedirs(folder)
    with io.open(full, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print("  wrote %-52s %6d bytes" % (path, len(text.encode("utf-8"))))


def offered_languages():
    """The codes the switcher actually offers, read out of i18n.js.

    A language that is commented out there renders as English, so listing it
    as an alternate would claim a translation that does not exist.
    """
    src = io.open(os.path.join(ROOT, "i18n.js"), encoding="utf-8").read()
    block = src[src.index("window.HOC_I18N.languages = ["):]
    block = block[:block.index("];")]
    codes = []
    for line in block.split("\n"):
        stripped = line.strip()
        if stripped.startswith("//") or "code:" not in stripped:
            continue
        code = stripped.split("code:", 1)[1].split('"')[1]
        if code not in codes:
            codes.append(code)
    return codes


def alternates(indent, close):
    codes = offered_languages()
    rows = ['%s<%s hreflang="en" href="%s/"%s' % (indent, TAG, SITE, close)]
    for code in sorted(c for c in codes if c != "en"):
        rows.append('%s<%s hreflang="%s" href="%s/?lang=%s"%s'
                    % (indent, TAG, code, SITE, code, close))
    rows.append('%s<%s hreflang="x-default" href="%s/"%s' % (indent, TAG, SITE, close))
    return rows, codes


def build_sitemap():
    global TAG
    TAG = 'xhtml:link rel="alternate"'
    alts, codes = alternates("    ", "/>")

    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" '
           'xmlns:xhtml="http://www.w3.org/1999/xhtml">',
           '  <url>',
           '    <loc>%s/</loc>' % SITE,
           '    <changefreq>monthly</changefreq>',
           '    <priority>1.0</priority>']
    out += alts
    out.append('  </url>')

    for path in ("case-studies/", "articles/"):
        out += ['  <url>',
                '    <loc>%s/%s</loc>' % (SITE, path),
                '    <changefreq>monthly</changefreq>',
                '    <priority>0.8</priority>',
                '  </url>']
    for cs in CASE_STUDIES:
        out += ['  <url>',
                '    <loc>%s/case-studies/%s.html</loc>' % (SITE, cs["slug"]),
                '    <priority>0.7</priority>',
                '  </url>']
    for art in ARTICLES:
        out += ['  <url>',
                '    <loc>%s/articles/%s.html</loc>' % (SITE, art["slug"]),
                '    <lastmod>%s</lastmod>' % art["date"],
                '    <priority>0.7</priority>',
                '  </url>']
    out.append('</urlset>')
    write("sitemap.xml", "\n".join(out) + "\n")
    write("robots.txt", "User-agent: *\nAllow: /\n\nSitemap: %s/sitemap.xml\n" % SITE)


def build_hreflang():
    """Keep index.html's alternate-language links to the languages on offer."""
    global TAG
    TAG = 'link rel="alternate"'
    rows, codes = alternates("", " />")

    path = os.path.join(ROOT, "index.html")
    html = io.open(path, encoding="utf-8").read()
    start = html.index('<link rel="alternate" hreflang="en"')
    end = html.index("/>", html.index('hreflang="x-default"')) + 2
    io.open(path, "w", encoding="utf-8", newline="").write(
        html[:start] + "\n".join(rows) + html[end:])
    print("  index.html hreflang %d language(s)" % len(codes))


def main():
    write("case-studies/index.html", case_studies_index())
    for i, cs in enumerate(CASE_STUDIES):
        others = CASE_STUDIES[i + 1:] + CASE_STUDIES[:i]
        write("case-studies/%s.html" % cs["slug"], case_study_page(cs, others[:3]))

    write("articles/index.html", articles_index())
    for i, art in enumerate(ARTICLES):
        others = ARTICLES[i + 1:] + ARTICLES[:i]
        write("articles/%s.html" % art["slug"], article_page(art, others[:3]))

    build_sitemap()
    build_hreflang()
    print("\n%d pages generated. Now run: python tools/csp.py" %
          (2 + len(CASE_STUDIES) + len(ARTICLES)))


if __name__ == "__main__":
    main()
