# -*- coding: utf-8 -*-
"""Generate the case-study and article pages.

    python tools/build.py          # from the repository root

The site itself has no build step: this writes plain HTML files that are
committed and served as-is. The generator exists only so that thirteen pages
share one header, one footer and one set of styles instead of drifting.

After running this, run tools/csp.py to refresh the inline-script hashes.
"""
import io
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from content import CASE_STUDIES, ARTICLES, ARTICLE_TAGS  # noqa: E402
from mocks import mock_for  # noqa: E402
import nav  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = "https://humansofcoding.com"

# The line drawings reused from the home page's project cards.
THUMBS = {
    "a": '<rect x="72" y="16" width="56" height="118" rx="10"/><path d="M92 26h16"/>'
         '<rect x="82" y="40" width="36" height="20" rx="5"/>'
         '<path d="M82 70h36M82 80h24M82 90h30"/>'
         '<rect x="82" y="104" width="36" height="14" rx="7"/>',
    "b": '<rect x="26" y="24" width="148" height="102" rx="8"/><path d="M26 44h148"/>'
         '<path d="M40 60h40M40 72h56M40 84h32"/>'
         '<rect x="112" y="60" width="48" height="34" rx="6"/>'
         '<rect x="40" y="98" width="40" height="12" rx="6"/>',
    "c": '<rect x="34" y="30" width="132" height="90" rx="8"/><path d="M34 52h132"/>'
         '<circle cx="70" cy="86" r="18"/><path d="M70 68v18l12 8"/>'
         '<path d="M104 74h50M104 88h50M104 102h30"/>',
}

BRAND_SVG = (
    '<svg viewBox="0 0 44 44" fill="none" stroke="currentColor" stroke-width="2.6" '
    'stroke-linecap="round" stroke-linejoin="round">'
    '<path d="M22 3.5c10.2 0 18.5 8.3 18.5 18.5S32.2 40.5 22 40.5 3.5 32.2 3.5 22 11.8 3.5 22 3.5Z"/>'
    '<path d="M15 18.5v9M15 22.6h6.5M21.5 18.2v9.2"/>'
    '<path d="M27 27.5c3.4 0 5.6-2.1 5.6-5.3S30.4 17 27 17"/></svg>'
)

MAILTO = ("mailto:adil@humansofcoding.com"
          "?subject=Free%20call%20request%20-%20HumansOfCoding")
INSTAGRAM = "https://instagram.com/humansofcoding"

# Both inline scripts are byte-identical to the ones in index.html, so the
# CSP hashes computed for that page cover these pages too.
HTTPS_SCRIPT = '''<script>
/* Send visitors to HTTPS. GitHub Pages' own "Enforce HTTPS" does this at the
   server level; this is the belt-and-braces version and is harmless once that
   setting is on (GitHub redirects first, so this never runs). Skipped for
   localhost and for opening the file directly from disk. */
(function () {
  var h = location.hostname;
  if (location.protocol === "http:" && h !== "localhost" && h !== "127.0.0.1") {
    location.replace("https://" + location.host + location.pathname + location.search + location.hash);
  }
})();
</script>'''

BOOT_SCRIPT = '''<script>
(function () {
  var d = document.documentElement, t = null, p = null;
  try {
    t = localStorage.getItem("hoc-theme");
    p = localStorage.getItem("hoc-palette");
  } catch (e) {}
  // never trust stored values verbatim
  if (t !== "dark" && t !== "light") t = null;
  if (["blue", "green", "slate", "ocean", "rainbow"].indexOf(p) === -1) p = "blue";
  d.classList.add("js");
  d.setAttribute("data-theme", t || (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light"));
  d.setAttribute("data-palette", p);
})();
</script>'''

BEACON = ('<!-- Cloudflare Web Analytics. Privacy-friendly and cookie-free: the numbers go\n'
          '     to the Cloudflare dashboard, not onto this page. The token is public. -->\n'
          '<script type="module" src="https://static.cloudflareinsights.com/beacon.min.js" '
          'data-cf-beacon=\'{"token": "16ba7bce6bf54d6fa4327ecd5912dfb1"}\'></script>')

CSP = ('<meta http-equiv="Content-Security-Policy" content="default-src \'self\'; '
       'base-uri \'self\'; object-src \'none\'; form-action \'none\'; '
       'script-src \'self\' https://static.cloudflareinsights.com {hashes}; '
       'style-src \'self\' \'unsafe-inline\'; font-src \'self\'; img-src \'self\' data:; '
       'connect-src \'self\' https://cloudflareinsights.com; upgrade-insecure-requests" />')


def head(title, description, canonical, jsonld):
    """The <head> for a page one directory below the site root."""
    return u'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />

<!--
  Content Security Policy. GitHub Pages cannot send real headers, so this is
  the meta form. The hashes cover the inline scripts below and are generated by
  tools/csp.py — regenerate them if you edit any inline script.
-->
{csp}
{https}
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
<meta name="referrer" content="strict-origin-when-cross-origin" />
<meta name="theme-color" content="#f6f9fd" media="(prefers-color-scheme: light)" />
<meta name="theme-color" content="#0b1219" media="(prefers-color-scheme: dark)" />

<title>{title}</title>
<meta name="description" content="{description}" />
<meta name="author" content="Adil — HumansOfCoding" />
<link rel="canonical" href="{canonical}" />

<meta property="og:type" content="article" />
<meta property="og:site_name" content="HumansOfCoding" />
<meta property="og:title" content="{title}" />
<meta property="og:description" content="{description}" />
<meta property="og:url" content="{canonical}" />
<meta property="og:image" content="{site}/assets/og-image.svg" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="{title}" />
<meta name="twitter:description" content="{description}" />
<meta name="twitter:image" content="{site}/assets/og-image.svg" />

<link rel="icon" href="../assets/favicon.svg" type="image/svg+xml" />
<link rel="apple-touch-icon" href="../assets/favicon.svg" />

<link rel="preload" href="../assets/fonts/inter-latin.woff2" as="font" type="font/woff2" crossorigin />
<link rel="preload" href="../assets/fonts/bricolage-grotesque-latin.woff2" as="font" type="font/woff2" crossorigin />
<link rel="stylesheet" href="../style.css" />

<!-- Tiny bootstrap: marks that JS is on and applies the saved theme before the
     first paint, so dark-mode users never see a flash of light. -->
{boot}

<script type="application/ld+json">
{jsonld}
</script>
</head>
'''.format(csp=CSP.format(hashes="{hashes}"), https=HTTPS_SCRIPT, boot=BOOT_SCRIPT,
           title=title, description=description, canonical=canonical,
           site=SITE, jsonld=jsonld)


def chrome_open(active):
    """Header, translation notice and mobile menu. `active` marks the nav item."""
    return u'''<body>
<a class="skip-link" href="#main">Skip to content</a>
<div class="progress" aria-hidden="true"><span id="progressBar"></span></div>

<header class="nav" id="nav">
  <div class="container nav__inner">
    <a class="brand" href="../index.html" aria-label="HumansOfCoding home">
      <span class="brand__mark" aria-hidden="true">{brand}</span>
      <span class="brand__text">HumansOfCoding</span>
    </a>

{primary}

    <div class="nav__actions">
      <div class="lang">
        <svg class="lang__globe" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c2.6 2.7 4 5.8 4 9s-1.4 6.3-4 9c-2.6-2.7-4-5.8-4-9s1.4-6.3 4-9Z"/></svg>
        <select class="lang__select" id="langSelect" aria-label="Language"></select>
        <svg class="lang__caret" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg>
      </div>
      <div class="appear">
        <button class="icon-btn" id="appearBtn" type="button" aria-label="Switch colour theme"
                aria-expanded="false" aria-haspopup="true" aria-controls="appearPanel">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <path d="M12 3a9 9 0 1 0 0 18c1 0 1.7-.8 1.7-1.7 0-.5-.2-.9-.5-1.2-.3-.3-.5-.7-.5-1.1 0-.9.8-1.7 1.7-1.7H16a5 5 0 0 0 5-5c0-4-4-7.3-9-7.3Z"/>
            <circle cx="7.6" cy="11.6" r="1.1" fill="currentColor" stroke="none"/>
            <circle cx="11" cy="7.4" r="1.1" fill="currentColor" stroke="none"/>
            <circle cx="16" cy="9" r="1.1" fill="currentColor" stroke="none"/>
          </svg>
        </button>

        <div class="appear__panel" id="appearPanel" hidden>
          <div class="appear__row" role="group" aria-label="Switch colour theme">
            <button type="button" class="appear__mode" data-mode="light" aria-label="Light">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><circle cx="12" cy="12" r="4.2"/><path d="M12 2.6v2.2M12 19.2v2.2M2.6 12h2.2M19.2 12h2.2M5.3 5.3l1.6 1.6M17.1 17.1l1.6 1.6M18.7 5.3l-1.6 1.6M6.9 17.1l-1.6 1.6"/></svg>
            </button>
            <button type="button" class="appear__mode" data-mode="dark" aria-label="Dark">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20 14.2A8.4 8.4 0 0 1 9.8 4a8.6 8.6 0 1 0 10.2 10.2Z"/></svg>
            </button>
            <button type="button" class="appear__mode" data-mode="system" aria-label="System">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="4.5" width="18" height="13" rx="2.5"/><path d="M9 21h6M12 17.5V21"/></svg>
            </button>
          </div>

          <div class="appear__row appear__row--swatches" role="group" aria-label="Colour">
            <button type="button" class="appear__sw" data-palette="blue" aria-label="Blue"><i style="background:#0f6ccc"></i></button>
            <button type="button" class="appear__sw" data-palette="green" aria-label="Green"><i style="background:#12784a"></i></button>
            <button type="button" class="appear__sw" data-palette="slate" aria-label="Slate"><i style="background:#445468"></i></button>
            <button type="button" class="appear__sw" data-palette="ocean" aria-label="Ocean"><i style="background:linear-gradient(135deg,#0b6a92,#38bdf8)"></i></button>
            <button type="button" class="appear__sw" data-palette="rainbow" aria-label="Rainbow"><i style="background:linear-gradient(100deg,#2563eb,#7028c8 34%,#c026d3 66%,#db2777)"></i></button>
          </div>
        </div>
      </div>
      <a class="btn btn--primary btn--sm nav__cta" data-link="call" href="{mailto}">Free Call</a>
      <button class="burger" id="burger" type="button" aria-label="Open menu" aria-expanded="false" aria-controls="mobileMenu">
        <span></span><span></span><span></span>
      </button>
    </div>
  </div>
</header>

<!-- Machine-translation notice (only shown when a translation is active) -->
<div class="tnote" id="transNote" hidden>
  <div class="container tnote__inner">
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 3.5 21 20H3l9-16.5Z"/><path d="M12 10v4M12 17h.01"/></svg>
    <p id="transNoteText"></p>
    <button type="button" id="transNoteLink" class="tnote__link"></button>
    <button type="button" id="transNoteOk" class="tnote__ok"></button>
  </div>
</div>

{mobilemenu}
    <div class="menu__cta">
      <a class="btn btn--primary btn--block" data-link="call" href="{mailto}">Book a Free Call</a>
      <a class="btn btn--ghost btn--block" data-link="instagram" href="{ig}">DM @humansofcoding</a>
    </div>
  </nav>
</div>

<main id="main">
'''.format(brand=BRAND_SVG, mailto=MAILTO, ig=INSTAGRAM,
           primary=nav.primary("../", active),
           mobilemenu=nav.mobile("../"))


CHROME_CLOSE = u'''</main>

<footer class="footer">
  <div class="container footer__inner">
    <div class="footer__brand">
      <a class="brand" href="../index.html" aria-label="HumansOfCoding home">
        <span class="brand__mark" aria-hidden="true">{brand}</span>
        <span class="brand__text">HumansOfCoding</span>
      </a>
      <p class="footer__tag">Apps • Websites • Software</p>
    </div>

    <nav class="footer__nav" aria-label="Footer">
      <a href="../index.html#services">Services</a>
      <a href="../index.html#mvp">MVP ₹20,000</a>
      <a href="../case-studies/index.html">Case Studies</a>
      <a href="../articles/index.html">Articles</a>
      <a href="../index.html#about">About</a>
      <a href="../index.html#contact">Contact</a>
    </nav>

    <div class="footer__social">
      <a class="footer__ig" data-link="instagram" href="{ig}">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5.5"/><circle cx="12" cy="12" r="4.2"/><path d="M17.4 6.6h.01"/></svg>
        @humansofcoding
      </a>
    </div>
  </div>
  <div class="container footer__bottom">
    <p>© 2026 HumansOfCoding. All rights reserved.</p>
    <p class="footer__made">Built by humans, in code. <span aria-hidden="true">✏️</span></p>
  </div>
</footer>

<div class="mobile-bar" id="mobileBar">
  <a class="btn btn--primary btn--block" data-link="call" href="{mailto}">Book a Free Call</a>
  <a class="mobile-bar__ig" data-link="instagram" href="{ig}" aria-label="DM us on Instagram">
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5.5"/><circle cx="12" cy="12" r="4.2"/><path d="M17.4 6.6h.01"/></svg>
  </a>
</div>

<script src="../i18n.js" defer></script>
<script src="../script.js" defer></script>

{beacon}
</body>
</html>
'''.format(brand=BRAND_SVG, mailto=MAILTO, ig=INSTAGRAM, beacon=BEACON)


def cta_block(title, sub):
    return u'''<section class="cta">
  <div class="container cta__inner">
    <h2 class="cta__title">{title}</h2>
    <p class="cta__sub">{sub}</p>
    <div class="cta__actions">
      <a class="btn btn--primary btn--lg" data-link="call" href="{mailto}">Book a FREE Call</a>
      <a class="btn btn--outline btn--lg" data-link="instagram" href="{ig}">DM @humansofcoding</a>
    </div>
    <p class="cta__note">Free 20-min idea call · No obligation</p>
  </div>
</section>
'''.format(title=title, sub=sub, mailto=MAILTO, ig=INSTAGRAM)


def breadcrumb(section, section_url, current):
    return u'''  <nav class="crumb" aria-label="Breadcrumb">
    <a href="../index.html">Home</a>
    <span aria-hidden="true">/</span>
    <a href="{url}">{section}</a>
    <span aria-hidden="true">/</span>
    <span aria-current="page">{current}</span>
  </nav>
'''.format(section=section, url=section_url, current=current)


# --------------------------------------------------------------------------
# case studies
# --------------------------------------------------------------------------

def page_hero(eyebrow, title, lead, crumbs, chips="", meta="", actions="", aside=""):
    """The banner band every sub-page opens with.

    It carries the same grid-and-blob backdrop as the home page hero, so a
    sub-page reads as part of the same site rather than a bolted-on blog.
    """
    split = " phero--split" if aside else ""
    return u'''<section class="phero{split}">
  <div class="phero__bg" aria-hidden="true">
    <span class="grid-fade"></span>
    <span class="blob blob--1"></span>
    <span class="blob blob--2"></span>
  </div>
  <div class="container phero__inner">
{crumbs}
    <div class="phero__grid">
      <div>
        <p class="eyebrow reveal" data-reveal><span class="eyebrow__dot" aria-hidden="true"></span>{eyebrow}</p>
{chips}
        <h1 class="phero__title reveal" data-reveal style="--d:.05s">{title}</h1>
        <p class="phero__lead reveal" data-reveal style="--d:.1s">{lead}</p>
{meta}
{actions}
      </div>
{aside}
    </div>
  </div>
</section>
'''.format(split=split, crumbs=crumbs, eyebrow=eyebrow, chips=chips, title=title, lead=lead,
           meta=meta, actions=actions, aside=aside)


def band(inner, alt=False, extra="", ident=""):
    """One full-width section. Alternating backgrounds give the page its rhythm."""
    classes = "section section--alt" if alt else "section"
    if extra:
        classes += " " + extra
    return u'<section class="%s"%s>\n  <div class="container">\n%s  </div>\n</section>\n\n' % (
        classes, (' id="%s"' % ident) if ident else "", inner)


def band_head(eyebrow, title, sub=""):
    out = u'''    <div class="sec-head">
      <p class="eyebrow reveal" data-reveal><span class="eyebrow__dot" aria-hidden="true"></span>{eyebrow}</p>
      <h2 class="sec-title reveal" data-reveal style="--d:.05s">{title}</h2>
'''.format(eyebrow=eyebrow, title=title)
    if sub:
        out += u'      <p class="sec-sub reveal" data-reveal style="--d:.1s">%s</p>\n' % sub
    return out + u'    </div>\n\n'


# --------------------------------------------------------------------------
# case studies
# --------------------------------------------------------------------------

def case_study_page(cs, others):
    plain = cs["title"].replace("&amp;", "and")
    jsonld = u'''{{
  "@context": "https://schema.org",
  "@type": "CreativeWork",
  "name": "{title}",
  "abstract": "{summary}",
  "creator": {{ "@type": "Organization", "name": "HumansOfCoding" }},
  "url": "{site}/case-studies/{slug}.html",
  "isAccessibleForFree": true,
  "disambiguatingDescription": "Example build. HumansOfCoding is a new studio; this describes a project the studio is set up to deliver, not completed client work."
}}'''.format(title=plain, summary=cs["summary"], site=SITE, slug=cs["slug"])

    out = [head("%s — Case Study | HumansOfCoding" % cs["title"],
                cs["summary"],
                "%s/case-studies/%s.html" % (SITE, cs["slug"]),
                jsonld),
           chrome_open("case-studies")]

    # ---- banner -----------------------------------------------------------
    crumbs = breadcrumb("Case Studies", "../case-studies/index.html", cs["title"])
    chips = ('    <span class="chips reveal" data-reveal>'
             '<span class="proj__flag">Example build</span>'
             '<span class="proj__cat">%s</span></span>\n' % cs["category"])
    actions = u'''    <div class="phero__actions reveal" data-reveal style="--d:.16s">
      <a class="btn btn--primary btn--lg" data-link="call" href="{mailto}">Build something like this</a>
      <a class="btn btn--outline btn--lg" href="../case-studies/index.html">All case studies</a>
    </div>
'''.format(mailto=MAILTO)
    aside = ('      <div class="phero__art reveal" data-reveal style="--d:.2s">'
             '%s</div>\n' % mock_for(cs["slug"]))
    out.append(page_hero("CASE STUDY", cs["title"], cs["summary"],
                         crumbs, chips=chips, actions=actions, aside=aside))

    # ---- at a glance ------------------------------------------------------
    glance = ['    <dl class="glance">\n']
    for i, (label, value) in enumerate(cs["glance"]):
        glance.append(u'''      <div class="glance__item reveal" data-reveal style="--d:.{d}s">
        <dt>{label}</dt>
        <dd>{value}</dd>
      </div>
'''.format(d=(i * 6) + 4, label=label, value=value))
    glance.append('    </dl>\n\n')
    glance.append(u'''    <p class="note note--flag reveal" data-reveal><strong>This is an example build.</strong>
    HumansOfCoding is a new studio with no client work to show yet. This page describes
    how the project would be scoped and built — the same thinking you would get on a real
    one. Nothing here is a past client, and no number on this page is a result.</p>
''')
    out.append(band("".join(glance), alt=True, extra="section--glance"))

    # ---- the situation ----------------------------------------------------
    inner = [band_head("THE SITUATION", "What's actually broken.")]
    inner.append('    <div class="split">\n      <div class="split__text">\n')
    for i, para in enumerate(cs["situation"]):
        inner.append('        <p class="reveal" data-reveal style="--d:.%ds">%s</p>\n'
                     % ((i * 6) + 4, para))
    # not .problem__list: the home page pins that class into grid column 1,
    # which would drop this list underneath the text instead of beside it
    inner.append('      </div>\n\n      <ul class="split__list">\n')
    for i, pain in enumerate(cs["pains"]):
        inner.append('        <li class="prob reveal" data-reveal style="--d:.%ds">'
                     '<span class="prob__x" aria-hidden="true">✕</span>'
                     '<h3>%s</h3></li>\n' % ((i * 6) + 6, pain))
    inner.append('      </ul>\n    </div>\n')
    out.append(band("".join(inner)))

    # ---- what we'd build --------------------------------------------------
    inner = [band_head("VERSION ONE", "What we'd build first.",
                       "Every item here earns its place by being something a real user "
                       "would miss on day one.")]
    inner.append('    <div class="cards cards--3">\n')
    for i, (name, body) in enumerate(cs["scope"]):
        inner.append(u'''      <article class="card card--service reveal" data-reveal style="--d:.{d}s">
        <span class="card__num" aria-hidden="true">{n:02d}</span>
        <h3>{name}</h3>
        <p>{body}</p>
        <span class="card__corner" aria-hidden="true"></span>
      </article>
'''.format(d=(i * 6) + 4, n=i + 1, name=name, body=body))
    inner.append('    </div>\n')
    out.append(band("".join(inner), alt=True))

    # ---- what we'd leave out ----------------------------------------------
    inner = [band_head("DELIBERATELY NOT IN V1", "What we'd leave out.",
                       "Not because these are bad ideas. Because each one is designed "
                       "better once the first version has told you something.")]
    inner.append('    <ul class="cutlist">\n')
    for i, item in enumerate(cs["excluded"]):
        inner.append('      <li class="reveal" data-reveal style="--d:.%ds">'
                     '<span class="cutlist__x" aria-hidden="true">✕</span>'
                     '<span>%s</span></li>\n' % ((i * 6) + 4, item))
    inner.append('    </ul>\n')
    out.append(band("".join(inner)))

    # ---- the stack --------------------------------------------------------
    inner = [band_head("UNDER THE HOOD", "How it's put together.")]
    inner.append('    <dl class="stack">\n')
    for i, (name, body) in enumerate(cs["stack"]):
        inner.append(u'''      <div class="stack__row reveal" data-reveal style="--d:.{d}s">
        <dt>{name}</dt>
        <dd>{body}</dd>
      </div>
'''.format(d=(i * 5) + 4, name=name, body=body))
    inner.append('    </dl>\n')
    out.append(band("".join(inner), alt=True))

    # ---- timeline ---------------------------------------------------------
    inner = [band_head("HOW IT RUNS", "Week by week.")]
    inner.append('    <ol class="timeline">\n'
                 '      <span class="tl__line" aria-hidden="true"><i></i></span>\n')
    for i, (when, what) in enumerate(cs["timeline"]):
        inner.append(u'''      <li class="tl reveal" data-reveal style="--d:.{d}s">
        <span class="tl__num">{n:02d}</span>
        <div class="tl__body">
          <h3>{when}</h3>
          <p>{what}</p>
        </div>
      </li>
'''.format(d=(i * 6) + 4, n=i + 1, when=when, what=what))
    inner.append('    </ol>\n')
    out.append(band("".join(inner)))

    # ---- the hardest part -------------------------------------------------
    hard_title, hard_paras = cs["hard"]
    inner = [band_head("THE HARD PART", hard_title,
                       "Every build has one problem that decides whether the rest "
                       "of it matters. This is that problem, written out.")]
    inner.append('    <div class="deep">\n')
    for i, para in enumerate(hard_paras):
        inner.append('      <p class="reveal" data-reveal style="--d:.%ds">%s</p>\n'
                     % ((i * 6) + 4, para))
    inner.append('    </div>\n')
    out.append(band("".join(inner)))

    # ---- what we'd ask before quoting -------------------------------------
    inner = [band_head("BEFORE A PRICE EXISTS", "What we'd ask you first.",
                       "A quote given without these answers is a guess. These are "
                       "the questions that actually move the number.")]
    inner.append('    <ol class="qlist">\n')
    for i, q in enumerate(cs["questions"]):
        inner.append('      <li class="reveal" data-reveal style="--d:.%ds">'
                     '<span class="qlist__n">%02d</span><span>%s</span></li>\n'
                     % ((i * 5) + 4, i + 1, q))
    inner.append('    </ol>\n')
    out.append(band("".join(inner), alt=True))

    # ---- how we'd know it worked ------------------------------------------
    inner = [band_head("AFTERWARDS", "How we'd know it worked.",
                       "Agreed before the build starts, so there is something to "
                       "judge it against other than whether it looks nice.")]
    inner.append('    <ul class="winlist">\n')
    for i, w in enumerate(cs["success"]):
        inner.append('      <li class="reveal" data-reveal style="--d:.%ds">'
                     '<span class="winlist__tick" aria-hidden="true">&#10003;</span>'
                     '<span>%s</span></li>\n' % ((i * 6) + 4, w))
    inner.append('    </ul>\n')
    out.append(band("".join(inner)))

    # ---- worth knowing + price -------------------------------------------
    inner = [band_head("BEFORE YOU START", "Worth knowing.")]
    inner.append(u'''    <div class="knowgrid">
      <p class="note reveal" data-reveal>{note}</p>
      <p class="note note--price reveal" data-reveal style="--d:.08s">MVPs start at
      <strong>₹20,000*</strong>. Final pricing depends on features and project scope.
      Third-party costs — cloud hosting, domains, external libraries, APIs, app-store
      fees and any other paid service — are billed separately and are not included.</p>
    </div>
'''.format(note=cs["note"]))
    out.append(band("".join(inner), alt=True))

    # ---- other builds -----------------------------------------------------
    inner = [band_head("KEEP LOOKING", "Other example builds.")]
    inner.append('    <div class="cards post-grid">\n')
    for i, other in enumerate(others):
        inner.append(u'''      <a class="card post-card reveal" data-reveal style="--d:.{d}s" href="{slug}.html">
        <span class="proj__cat">{cat}</span>
        <h3>{title}</h3>
        <p>{summary}</p>
        <span class="link-arrow">Read the case study <span aria-hidden="true">→</span></span>
      </a>
'''.format(d=(i * 6) + 4, slug=other["slug"], cat=other["category"],
           title=other["title"], summary=other["summary"]))
    inner.append('    </div>\n')
    out.append(band("".join(inner)))

    out.append(cta_block("Want this built for your business?",
                         "Tell us what you're thinking. We'll figure out the next step together."))
    out.append(CHROME_CLOSE)
    return "".join(out)


def case_studies_index():
    jsonld = u'''{
  "@context": "https://schema.org",
  "@type": "CollectionPage",
  "name": "Case Studies — HumansOfCoding",
  "description": "Example builds showing how HumansOfCoding scopes and ships apps, websites and custom software.",
  "url": "%s/case-studies/"
}''' % SITE

    out = [head("Case Studies — Example Builds | HumansOfCoding",
                "How we scope and build apps, websites, dashboards and MVPs — "
                "six example builds with the scope, the stack, the timeline and "
                "what we would deliberately leave out of version one.",
                "%s/case-studies/" % SITE, jsonld),
           chrome_open("case-studies")]

    crumbs = u'''    <nav class="crumb" aria-label="Breadcrumb">
      <a href="../index.html">Home</a>
      <span aria-hidden="true">/</span>
      <span aria-current="page">Case Studies</span>
    </nav>
'''
    out.append(page_hero("WHAT WE BUILD", "Case studies",
                         "Six builds, taken apart. What the business problem is, what "
                         "version one contains, what gets cut, how it's put together "
                         "and how long it runs.", crumbs))

    inner = [u'''    <p class="note note--flag reveal" data-reveal><strong>Straight up: these are example builds.</strong>
    HumansOfCoding is new, so none of these are past clients and nothing here is a
    results claim. They're the products the studio is set up to ship, written out in
    the same detail you'd get on a real project. Yours would be the first on this wall.</p>

    <div class="cards post-grid">
''']
    for i, cs in enumerate(CASE_STUDIES):
        inner.append(u'''      <a class="card post-card reveal" data-reveal style="--d:.{d}s" href="{slug}.html">
        <div class="post-card__mock">{mock}</div>
        <span class="chips"><span class="proj__flag">Example build</span><span class="proj__cat">{cat}</span></span>
        <h2>{title}</h2>
        <p>{summary}</p>
        <span class="link-arrow">Read the case study <span aria-hidden="true">→</span></span>
      </a>
'''.format(d=(i * 6) + 4, slug=cs["slug"], mock=mock_for(cs["slug"], bare=True),
           cat=cs["category"], title=cs["title"], summary=cs["summary"]))
    inner.append('    </div>\n')
    out.append(band("".join(inner), alt=True))

    inner = [band_head("HOW IT WORKS", "Every one of these starts the same way.")]
    inner.append(u'''    <ol class="timeline">
      <span class="tl__line" aria-hidden="true"><i></i></span>
      <li class="tl reveal" data-reveal><span class="tl__num">01</span>
        <div class="tl__body"><h3>Tell us your idea</h3>
        <p>Book a free call and tell us what you want to build.</p></div></li>
      <li class="tl reveal" data-reveal style="--d:.08s"><span class="tl__num">02</span>
        <div class="tl__body"><h3>Plan</h3>
        <p>We define the features, scope and best technical approach.</p></div></li>
      <li class="tl reveal" data-reveal style="--d:.16s"><span class="tl__num">03</span>
        <div class="tl__body"><h3>Build</h3>
        <p>We design and develop your product.</p></div></li>
      <li class="tl reveal" data-reveal style="--d:.24s"><span class="tl__num">04</span>
        <div class="tl__body"><h3>Launch</h3>
        <p>Get it in front of real users and start growing.</p></div></li>
    </ol>
''')
    out.append(band("".join(inner)))

    out.append(cta_block("Want to be project #001?",
                         "Tell us what you're thinking. We'll figure out the next step together."))
    out.append(CHROME_CLOSE)
    return "".join(out)


def render_blocks(blocks):
    out = []
    for kind, value in blocks:
        if kind == "h2":
            out.append(u"    <h2>%s</h2>\n" % value)
        elif kind == "p":
            out.append(u"    <p>%s</p>\n" % value)
        elif kind == "quote":
            out.append(u"    <blockquote><p>%s</p></blockquote>\n" % value)
        elif kind in ("ul", "ol"):
            out.append(u"    <%s>\n" % kind)
            for item in value:
                out.append(u"      <li>%s</li>\n" % item)
            out.append(u"    </%s>\n" % kind)
    return "".join(out)


def article_page(art, others):
    jsonld = u'''{{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "headline": "{title}",
  "description": "{summary}",
  "datePublished": "{date}",
  "author": {{ "@type": "Person", "name": "Adil" }},
  "publisher": {{ "@type": "Organization", "name": "HumansOfCoding" }},
  "mainEntityOfPage": "{site}/articles/{slug}.html",
  "inLanguage": "en"
}}'''.format(title=art["title"], summary=art["summary"], date=art["date"],
             site=SITE, slug=art["slug"])

    out = [head("%s | HumansOfCoding" % art["title"], art["summary"],
                "%s/articles/%s.html" % (SITE, art["slug"]), jsonld),
           chrome_open("articles")]

    crumbs = breadcrumb("Articles", "../articles/index.html", art["title"])
    chips = ('    <span class="chips reveal" data-reveal>'
             '<span class="proj__cat">%s</span></span>\n' % art["tag"])
    meta = u'''    <p class="phero__meta reveal" data-reveal style="--d:.14s">
      <span>By Adil</span>
      <span aria-hidden="true">·</span>
      <time datetime="{date}">{date_label}</time>
      <span aria-hidden="true">·</span>
      <span>{read}</span>
    </p>
'''.format(date=art["date"], date_label=art["date_label"], read=art["read"])
    out.append(page_hero("ARTICLE", art["title"], art["summary"],
                         crumbs, chips=chips, meta=meta))

    # The body is the one place a narrow reading column is right, so it keeps
    # its own band rather than being broken into more of them.
    out.append(u'<section class="section section--read">\n  <div class="container prose">\n')
    if art.get("caveat"):
        # version-specific detail dates fast, so say so rather than let a reader
        # act on something that moved after this was written
        out.append(
            u'    <p class="note note--flag"><strong>Written {when}.</strong> This one '
            u'touches fast-moving tooling. The tradeoffs should hold; check anything '
            u'version-specific against current documentation before relying on '
            u'it.</p>\n'.format(when=art["date_label"]))
    out.append(render_blocks(art["body"]))
    out.append(u'''  </div>
</section>

''')

    inner = [band_head("KEEP READING", "More articles.")]
    inner.append('    <div class="cards post-grid">\n')
    for i, other in enumerate(others):
        inner.append(u'''      <a class="card post-card reveal" data-reveal style="--d:.{d}s" href="{slug}.html">
        <span class="proj__cat">{tag}</span>
        <h3>{title}</h3>
        <p>{summary}</p>
        <p class="post-card__meta"><time datetime="{date}">{date_label}</time> · {read}</p>
        <span class="link-arrow">Read it <span aria-hidden="true">→</span></span>
      </a>
'''.format(d=(i * 6) + 4, slug=other["slug"], tag=other["tag"], title=other["title"],
           summary=other["summary"], date=other["date"],
           date_label=other["date_label"], read=other["read"]))
    inner.append('    </div>\n')
    out.append(band("".join(inner), alt=True))

    out.append(cta_block("Got an idea you've been sitting on?",
                         "Book a free call. Worst case, you walk away with free advice on what to build first."))
    out.append(CHROME_CLOSE)
    return "".join(out)


def articles_index():
    jsonld = u'''{
  "@context": "https://schema.org",
  "@type": "Blog",
  "name": "Articles — HumansOfCoding",
  "description": "Plain-English writing about building software: MVPs, pricing, apps versus websites, and how AI actually fits into the work.",
  "url": "%s/articles/"
}''' % SITE

    out = [head("Articles — Plain-English Writing on Building Software | HumansOfCoding",
                "MVPs, what software actually costs, apps versus websites, and how "
                "AI fits into real engineering. Written by Adil, no jargon.",
                "%s/articles/" % SITE, jsonld),
           chrome_open("articles")]

    crumbs = u'''    <nav class="crumb" aria-label="Breadcrumb">
      <a href="../index.html">Home</a>
      <span aria-hidden="true">/</span>
      <span aria-current="page">Articles</span>
    </nav>
'''
    out.append(page_hero("WRITING", "Articles",
                         "What I've learned building software for eleven years, "
                         "written for the person paying for it rather than the person "
                         "writing it.", crumbs))

    # Topic filter. Eleven articles is past the point where a flat list works,
    # and the counts tell a reader what is actually here before they click.
    chips = ['      <button type="button" class="chip is-on" data-filter="all"'
             ' aria-pressed="true">All <span class="chip__n">%d</span></button>'
             % len(ARTICLES)]
    for tag in ARTICLE_TAGS:
        n = len([a for a in ARTICLES if a["tag"] == tag])
        chips.append('      <button type="button" class="chip" data-filter="%s"'
                     ' aria-pressed="false">%s <span class="chip__n">%d</span></button>'
                     % (tag, tag, n))

    inner = ['    <div class="chips-bar" role="group" aria-label="Filter articles by topic" id="artFilter">\n',
             "\n".join(chips),
             '\n    </div>\n\n',
             '    <div class="cards post-grid" id="artGrid">\n']
    for i, art in enumerate(ARTICLES):
        inner.append(u'''      <a class="card post-card reveal" data-reveal style="--d:.{d}s" href="{slug}.html" data-tag="{tag}">
        <span class="proj__cat">{tag}</span>
        <h2>{title}</h2>
        <p>{summary}</p>
        <p class="post-card__meta"><time datetime="{date}">{date_label}</time> · {read}</p>
        <span class="link-arrow">Read it <span aria-hidden="true">→</span></span>
      </a>
'''.format(d=(i * 6) + 4, slug=art["slug"], tag=art["tag"], title=art["title"],
           summary=art["summary"], date=art["date"], date_label=art["date_label"],
           read=art["read"]))
    inner.append('    </div>\n')
    out.append(band("".join(inner), alt=True))

    out.append(cta_block("Rather just ask a person?",
                         "Book a free 20-minute call and ask whatever you like. No obligation."))
    out.append(CHROME_CLOSE)
    return "".join(out)


def write(path, text):
    full = os.path.join(ROOT, path)
    folder = os.path.dirname(full)
    if not os.path.isdir(folder):
        os.makedirs(folder)
    with io.open(full, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print("  wrote %-52s %6d bytes" % (path, len(text.encode("utf-8"))))


def offered_languages():
    """The codes the switcher actually offers, read out of i18n.js.

    A language that is commented out there renders as English, so listing it
    as an alternate would claim a translation that does not exist.
    """
    src = io.open(os.path.join(ROOT, "i18n.js"), encoding="utf-8").read()
    block = src[src.index("window.HOC_I18N.languages = ["):]
    block = block[:block.index("];")]
    codes = []
    for line in block.split("\n"):
        stripped = line.strip()
        if stripped.startswith("//") or "code:" not in stripped:
            continue
        code = stripped.split("code:", 1)[1].split('"')[1]
        if code not in codes:
            codes.append(code)
    return codes


def alternates(indent, close):
    codes = offered_languages()
    rows = ['%s<%s hreflang="en" href="%s/"%s' % (indent, TAG, SITE, close)]
    for code in sorted(c for c in codes if c != "en"):
        rows.append('%s<%s hreflang="%s" href="%s/?lang=%s"%s'
                    % (indent, TAG, code, SITE, code, close))
    rows.append('%s<%s hreflang="x-default" href="%s/"%s' % (indent, TAG, SITE, close))
    return rows, codes


def build_sitemap():
    global TAG
    TAG = 'xhtml:link rel="alternate"'
    alts, codes = alternates("    ", "/>")

    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" '
           'xmlns:xhtml="http://www.w3.org/1999/xhtml">',
           '  <url>',
           '    <loc>%s/</loc>' % SITE,
           '    <changefreq>monthly</changefreq>',
           '    <priority>1.0</priority>']
    out += alts
    out.append('  </url>')

    for path in ("case-studies/", "articles/"):
        out += ['  <url>',
                '    <loc>%s/%s</loc>' % (SITE, path),
                '    <changefreq>monthly</changefreq>',
                '    <priority>0.8</priority>',
                '  </url>']
    for cs in CASE_STUDIES:
        out += ['  <url>',
                '    <loc>%s/case-studies/%s.html</loc>' % (SITE, cs["slug"]),
                '    <priority>0.7</priority>',
                '  </url>']
    for art in ARTICLES:
        out += ['  <url>',
                '    <loc>%s/articles/%s.html</loc>' % (SITE, art["slug"]),
                '    <lastmod>%s</lastmod>' % art["date"],
                '    <priority>0.7</priority>',
                '  </url>']
    out.append('</urlset>')
    write("sitemap.xml", "\n".join(out) + "\n")
    write("robots.txt", "User-agent: *\nAllow: /\n\nSitemap: %s/sitemap.xml\n" % SITE)


def build_nav():
    """Rewrite index.html's nav from nav.py, so the home page and the generated
    pages can never drift apart."""
    path = os.path.join(ROOT, "index.html")
    html = io.open(path, encoding="utf-8").read()

    start = html.index('    <nav class="nav__links" aria-label="Primary">')
    end = html.index("</nav>", start) + len("</nav>")
    html = html[:start] + nav.primary("") + html[end:]

    start = html.index('<div class="menu" id="mobileMenu" hidden>')
    end = html.index('    <div class="menu__cta">', start)
    html = html[:start] + nav.mobile("") + "\n" + html[end:]

    io.open(path, "w", encoding="utf-8", newline="").write(html)
    print("  index.html nav rebuilt")


def build_hreflang():
    """Keep index.html's alternate-language links to the languages on offer."""
    global TAG
    TAG = 'link rel="alternate"'
    rows, codes = alternates("", " />")

    path = os.path.join(ROOT, "index.html")
    html = io.open(path, encoding="utf-8").read()
    start = html.index('<link rel="alternate" hreflang="en"')
    end = html.index("/>", html.index('hreflang="x-default"')) + 2
    io.open(path, "w", encoding="utf-8", newline="").write(
        html[:start] + "\n".join(rows) + html[end:])
    print("  index.html hreflang %d language(s)" % len(codes))


def main():
    write("case-studies/index.html", case_studies_index())
    for i, cs in enumerate(CASE_STUDIES):
        others = CASE_STUDIES[i + 1:] + CASE_STUDIES[:i]
        write("case-studies/%s.html" % cs["slug"], case_study_page(cs, others[:3]))

    write("articles/index.html", articles_index())
    for i, art in enumerate(ARTICLES):
        others = ARTICLES[i + 1:] + ARTICLES[:i]
        write("articles/%s.html" % art["slug"], article_page(art, others[:3]))

    build_sitemap()
    build_hreflang()
    build_nav()
    print("\n%d pages generated. Now run: python tools/csp.py" %
          (2 + len(CASE_STUDIES) + len(ARTICLES)))


if __name__ == "__main__":
    main()
